/*
 * Title:  spider (Linux)
 * Author: Shuichiro Endo
 */

#ifndef SPIDER_H_
#define SPIDER_H_

//#define _DEBUG

#define NODE_BUFFER_SIZE 65535

#define ROUTING_MESSAGE_DATA_SIZE 60000
#define SOCKS5_MESSAGE_DATA_SIZE 60000

#define ROUTING_MESSAGE_QUEUE_CAPACITY 100
#define SOCKS5_MESSAGE_QUEUE_CAPACITY 100

#define KEYS_MAP_SIZE 200
#define DELETE_ROUTE_TIME 5 // 5s

#define SPIDER_COMMAND_ADD_NODE_SPIDER_CLIENT  1
#define SPIDER_COMMAND_ADD_NODE_SPIDER_PIPE    2
#define SPIDER_COMMAND_SHOW_NODE_INFORMATION   3
#define SPIDER_COMMAND_SHOW_ROUTING_TABLE      4
#define SPIDER_COMMAND_EXIT                    0

#endif /* SPIDER_H_ */

